ProjetoFinanceiro/ProjetoFinanceiro.Web/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjetoFinanceiro.Web.Models;
using System.Net.Http;
using System.Security.Policy;
using System.Text;

namespace ProjetoFinanceiro.Web.Controllers
{
    public class ClienteController : Controller
    {
        private readonly string ENDPOINT = "";
        private readonly HttpClient _httpClient = null;
        private readonly IConfiguration _configuration;

        public ClienteController(IConfiguration configuration)
        {
            _configuration = configuration;
            ENDPOINT = _configuration["WebConfig:Endpoints:Url_Api"];

            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(ENDPOINT);
        }

        public async Task<IActionResult> Index()
        {

            try
            {
                List<ClienteViewModel> clientes = null;

                HttpResponseMessage response = await _httpClient.GetAsync(ENDPOINT);
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    clientes = JsonConvert.DeserializeObject<List<ClienteViewModel>>(content);
                }
                else
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitacao");
                }

                return View(clientes);
            }
            catch (Exception ex)
            {
                string message = ex.Message;
                throw ex;
            }

        }


        public async Task<IActionResult> Get(int id)
        {
            try
            {
                ClienteViewModel result = await Pesquisar(id);

                return View(result);
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create([Bind("Nome, Cpf")] ClienteViewModel cliente)
        {
            try
            {
                string json = JsonConvert.SerializeObject(cliente);
                byte[] buffer = Encoding.UTF8.GetBytes(json);
                ByteArrayContent byteArrayContent = new ByteArrayContent(buffer);
                byteArrayContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

                string url = ENDPOINT;
                HttpResponseMessage response =
                    await _httpClient.PostAsync(url, byteArrayContent);

                if (!response.IsSuccessStatusCode)
                    ModelState.AddModelError(null, "Erro ao processar a solicitacao");

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }


        public async Task<IActionResult> Edit(int id)
        {
            ClienteViewModel cliente = await Pesquisar(id);

            return View(cliente);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("ClienteId, Nome, Cpf")] ClienteViewModel cliente)
        {
            try
            {
                string json = JsonConvert.SerializeObject(cliente);
                byte[] buffer = Encoding.UTF8.GetBytes(json);
                ByteArrayContent byteArrayContent = new ByteArrayContent(buffer);
                byteArrayContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

                string url = ENDPOINT;

                HttpResponseMessage response =
                       await _httpClient.PostAsync(url, byteArrayContent);

                if (!response.IsSuccessStatusCode)
                    ModelState.AddModelError(null, "Erro ao processar a solicitacao");

                return RedirectToAction("Index");

            }
            catch (Exception)
            {

                throw;
            }

        }

        public async Task<IActionResult> Delete(int id)
        {
            ClienteViewModel cliente = await Pesquisar(id);

            if (cliente == null)
                return NotFound();

            return View(cliente);
        }



        public async Task<IActionResult> Delete2(string ClienteId)
        {

            int id = Convert.ToInt32(ClienteId); //int32.Parse(ClienteId)
            string url = $"{ENDPOINT}{id}";

            HttpResponseMessage response =
                           await _httpClient.DeleteAsync(url);

            if (!response.IsSuccessStatusCode)
                ModelState.AddModelError(null, "Erro ao processar a solicitacao");
            return RedirectToAction("Index");
        }


        #region Metodos auxilares
        private async Task<ClienteViewModel> Pesquisar(int id)
        {
            try
            {
                ClienteViewModel result = null;

                string url = $"{ENDPOINT}{id}";
                HttpResponseMessage response = await _httpClient.GetAsync(url);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    result = JsonConvert.DeserializeObject<ClienteViewModel>(content);
                }
                else
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitacao");
                }

                return result;
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        #endregion
    }
}

ProjetoFinanceiro/ProjetoFinanceiro.Web/Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoFinanceiro.Web.Models.Dtos;

namespace ProjetoFinanceiro.Web.Controllers
{
    public class PessoaController : Controller
    {
        private static List<PessoaDto> _pessoas = null;

        public PessoaController()
        {
            if (_pessoas == null)
                CarregarPessoas();
        }
        private void CarregarPessoas()
        {
            _pessoas = new List<PessoaDto>();

            PessoaDto pessoa1 = new PessoaDto
            {
                Id = Guid.NewGuid().ToString(),
                Nome = "Jose Robeto",
                Email = "jose@gmail.com"

            };

            _pessoas.Add(pessoa1);

            PessoaDto pessoa2 = new PessoaDto
            {
                Id = Guid.NewGuid().ToString(),
                Nome = "Jose Beto",
                Email = "beto@gmail.com"

            };

            _pessoas.Add(pessoa2);

            PessoaDto pessoa3 = new PessoaDto
            {
                Id = Guid.NewGuid().ToString(),
                Nome = "Jose ",
                Email = "beto@gmail.com"

            };

            _pessoas.Add(pessoa3);
        }


        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Listar()
        {
            return View(_pessoas);

        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("Nome, Email")] PessoaDto pessoa)
        {
            try
            {
                pessoa.Id = Guid.NewGuid().ToString();
                _pessoas.Add(pessoa);

                return RedirectToAction("Listar");
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            PessoaDto pessoa = _pessoas.FirstOrDefault(p => p.Id == id);
            return View(pessoa);
        }

        [HttpPost]
        public IActionResult Delete2(string id)
        {
            PessoaDto pessoa = _pessoas.FirstOrDefault(p => p.Id == id);
            if (pessoa != null)
                _pessoas.Remove(pessoa);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            PessoaDto pessoa = _pessoas.FirstOrDefault(p => p.Id.Equals(id));
            
            return View(pessoa);
        }

        [HttpPost]
        public IActionResult Edit([Bind("Id", "Nome, Email")] PessoaDto pessoa)
        {

            PessoaDto pessoapesquisa = _pessoas.FirstOrDefault(p => p.Id.Equals(pessoa.Id));

            if (pessoapesquisa != null)
            {
                _pessoas.Remove(pessoapesquisa);
                _pessoas.Add(pessoa);
            }
             

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            PessoaDto pessoa = _pessoas.FirstOrDefault(p => p.Id.Equals(id));

            return View(pessoa);
        }

    }
}

ProjetoFinanceiro/ProjetoFinanceiro.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoFinanceiro.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoFinanceiro.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoFinanceiro.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Listar">Pessoas</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetoFinanceiro.Web 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>